# Generated by Django 4.0 on 2022-03-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_product_orderplaced_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='satus',
            new_name='status',
        ),
    ]
