# Generated by Django 4.0 on 2022-04-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
            ],
        ),
    ]
